export interface DummyPost {
  _id: string;
  title: string;
  slug: { current: string };
  heroImageUrl: string;
  mainImage?: { asset: { _ref: string }; alt?: string };
  excerpt: string;
  publishedAt: string;
  categories: { _id: string; title: string }[];
  author: { name: string };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  body: any[];
}

export const DUMMY_POSTS: DummyPost[] = [
  {
    _id: 'dummy-1',
    title: 'Why Your Brand Needs a Growth-Driven Digital Strategy in 2025',
    slug: { current: 'dummy-growth-driven-digital-strategy' },
    heroImageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1920&q=90&auto=format&fit=crop',
    excerpt:
      "In an era of fragmented attention, a unified digital approach isn't optional — it's essential for survival and long-term brand equity.",
    publishedAt: '2025-02-10',
    categories: [{ _id: 'cat-strategy', title: 'Strategy' }],
    author: { name: 'Digitally Next' },
    body: [
      { _type: 'block', style: 'normal', _key: 'b1', children: [{ _type: 'span', _key: 's1', text: "The digital landscape has changed. Attention is fragmented across more surfaces than ever, and brands that rely on isolated campaigns are losing ground to those who build coherent, connected digital ecosystems. A growth-driven strategy isn't a luxury — it's the baseline." }] },
      { _type: 'block', style: 'h2', _key: 'b2', children: [{ _type: 'span', _key: 's2', text: 'What Growth-Driven Actually Means' }] },
      { _type: 'block', style: 'normal', _key: 'b3', children: [{ _type: 'span', _key: 's3', text: "Growth-driven digital strategy means every channel, every piece of content, and every campaign is oriented toward measurable business outcomes. Not impressions. Not clicks. Outcomes. Your SEO informs your paid strategy. Your content feeds your CRM. Your website is architected to convert, not just to exist." }] },
      { _type: 'block', style: 'h2', _key: 'b4', children: [{ _type: 'span', _key: 's4', text: 'The Brands Winning in 2025' }] },
      { _type: 'block', style: 'normal', _key: 'b5', children: [{ _type: 'span', _key: 's5', text: "The brands winning this year invested in integrated infrastructure two years ago. They built systems, not campaigns. They hired for strategy before execution. And they made data the decision-maker at every layer of their marketing." }] },
      { _type: 'block', style: 'h2', _key: 'b6', children: [{ _type: 'span', _key: 's6', text: 'How to Get Started' }] },
      { _type: 'block', style: 'normal', _key: 'b7', children: [{ _type: 'span', _key: 's7', text: "Start with an audit of your current channels. Map every touchpoint to a business outcome. Identify where data is siloed and where integration is missing. Then build a 90-day plan that connects the gaps — channel by channel, system by system." }] },
      { _type: 'block', style: 'h2', _key: 'faq0', children: [{ _type: 'span', _key: 's8', text: 'Frequently Asked Questions' }] },
      { _type: 'block', style: 'h3', _key: 'faq1', children: [{ _type: 'span', _key: 's9', text: 'What is a growth-driven digital strategy?' }] },
      { _type: 'block', style: 'normal', _key: 'faq1a', children: [{ _type: 'span', _key: 's10', text: "It's an approach where every digital channel, campaign, and asset is tied directly to measurable business outcomes — revenue, qualified leads, customer retention — rather than platform-level vanity metrics like impressions or reach." }] },
      { _type: 'block', style: 'h3', _key: 'faq2', children: [{ _type: 'span', _key: 's11', text: 'How long does it take to see results?' }] },
      { _type: 'block', style: 'normal', _key: 'faq2a', children: [{ _type: 'span', _key: 's12', text: "Foundational changes — data infrastructure, channel integration, measurement setup — typically take 60–90 days. Compounding returns from a growth-driven approach are usually visible within 6 months of consistent execution." }] },
      { _type: 'block', style: 'h3', _key: 'faq3', children: [{ _type: 'span', _key: 's13', text: 'Is this only for large brands?' }] },
      { _type: 'block', style: 'normal', _key: 'faq3a', children: [{ _type: 'span', _key: 's14', text: "Not at all. Mid-market and D2C brands often see the highest ROI from a growth-driven approach precisely because they're lean enough to implement changes quickly without large organizational overhead." }] },
    ],
  },
  {
    _id: 'dummy-2',
    title: 'The Modern DAD Framework: How We Use Data, AI & Digital',
    slug: { current: 'dummy-dad-framework' },
    heroImageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1920&q=90&auto=format&fit=crop',
    excerpt: 'Our proprietary framework that transforms how brands make decisions and execute campaigns at scale — with measurable outcomes.',
    publishedAt: '2025-01-28',
    categories: [{ _id: 'cat-thought', title: 'Thought Leadership' }],
    author: { name: 'Digitally Next' },
    body: [
      { _type: 'block', style: 'normal', _key: 'b1', children: [{ _type: 'span', _key: 's1', text: "At Digitally Next, we operate on a framework we call DAD — Data, AI, and Digital. It's a structured approach to how brands should think about modern marketing infrastructure, from the first brief to the final attribution report." }] },
      { _type: 'block', style: 'h2', _key: 'b2', children: [{ _type: 'span', _key: 's2', text: 'D — Data Shapes Decisions' }] },
      { _type: 'block', style: 'normal', _key: 'b3', children: [{ _type: 'span', _key: 's3', text: "Before any campaign is launched, data defines the brief. Audience intelligence, competitive gaps, channel attribution, and first-party signals all feed into a strategic foundation that keeps execution honest and accountable." }] },
      { _type: 'block', style: 'h2', _key: 'b4', children: [{ _type: 'span', _key: 's4', text: 'A — AI Accelerates Execution' }] },
      { _type: 'block', style: 'normal', _key: 'b5', children: [{ _type: 'span', _key: 's5', text: "AI doesn't replace strategy — it amplifies it. From content generation to predictive bidding to automated reporting, AI gives our teams leverage to focus on judgment rather than repetition." }] },
      { _type: 'block', style: 'h2', _key: 'b6', children: [{ _type: 'span', _key: 's6', text: 'D — Digital Systems Deliver Outcomes' }] },
      { _type: 'block', style: 'normal', _key: 'b7', children: [{ _type: 'span', _key: 's7', text: "The third D is the delivery layer — the websites, platforms, and automation flows where strategy meets execution. Without robust digital infrastructure, the best data and AI can't produce compounding results." }] },
      { _type: 'block', style: 'h2', _key: 'faq0', children: [{ _type: 'span', _key: 's8', text: 'Frequently Asked Questions' }] },
      { _type: 'block', style: 'h3', _key: 'faq1', children: [{ _type: 'span', _key: 's9', text: 'Is the DAD framework only for digital-native companies?' }] },
      { _type: 'block', style: 'normal', _key: 'faq1a', children: [{ _type: 'span', _key: 's10', text: "No. DAD is particularly effective for traditional businesses making the transition to digital-first operations, because it provides a structured path from where they are to where they need to be — without requiring a complete overhaul on day one." }] },
      { _type: 'block', style: 'h3', _key: 'faq2', children: [{ _type: 'span', _key: 's11', text: 'How does AI fit into the framework practically?' }] },
      { _type: 'block', style: 'normal', _key: 'faq2a', children: [{ _type: 'span', _key: 's12', text: "Practically, AI in the DAD framework means using tools like predictive analytics, automated content testing, and smart bidding — not generative AI for its own sake. Every AI application is tied to a specific efficiency or outcome goal." }] },
      { _type: 'block', style: 'h3', _key: 'faq3', children: [{ _type: 'span', _key: 's13', text: 'Can small teams implement DAD?' }] },
      { _type: 'block', style: 'normal', _key: 'faq3a', children: [{ _type: 'span', _key: 's14', text: "Absolutely. The DAD framework scales to team size. A two-person marketing team can apply DAD principles by starting with clean data collection, one AI automation tool, and a single well-integrated digital channel." }] },
    ],
  },
  {
    _id: 'dummy-3',
    title: 'Performance Marketing Beyond Clicks: Measuring Real Impact',
    slug: { current: 'dummy-performance-marketing' },
    heroImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1920&q=90&auto=format&fit=crop',
    excerpt: 'Why vanity metrics are killing your ROI and how to build measurement frameworks that actually matter to your business.',
    publishedAt: '2025-01-15',
    categories: [{ _id: 'cat-perf', title: 'Performance' }],
    author: { name: 'Digitally Next' },
    body: [
      { _type: 'block', style: 'normal', _key: 'b1', children: [{ _type: 'span', _key: 's1', text: "Clicks, impressions, and reach are comfortable numbers. They're easy to report, easy to scale, and easy to hide behind when the business isn't growing. Real performance marketing starts when you stop optimising for platform metrics and start optimising for business outcomes." }] },
      { _type: 'block', style: 'h2', _key: 'b2', children: [{ _type: 'span', _key: 's2', text: 'The Metric Trap' }] },
      { _type: 'block', style: 'normal', _key: 'b3', children: [{ _type: 'span', _key: 's3', text: "Most brands are measuring the wrong things. A 3% CTR on a campaign that drives zero qualified leads isn't performance — it's activity. The shift to outcome-based measurement requires connecting your ad platforms to your CRM, your CRM to your revenue data, and your revenue data back to your acquisition cost." }] },
      { _type: 'block', style: 'h2', _key: 'b4', children: [{ _type: 'span', _key: 's4', text: 'Building a Measurement Stack That Works' }] },
      { _type: 'block', style: 'normal', _key: 'b5', children: [{ _type: 'span', _key: 's5', text: "Start with clean first-party data. Layer in GA4 with proper event architecture. Build conversion paths that track intent, not just action. And review attribution models quarterly — the channel mix that worked six months ago may not reflect how your customers discover you today." }] },
      { _type: 'block', style: 'h2', _key: 'b6', children: [{ _type: 'span', _key: 's6', text: 'The Metrics That Actually Matter' }] },
      { _type: 'block', style: 'normal', _key: 'b7', children: [{ _type: 'span', _key: 's7', text: "Cost per qualified lead, revenue per channel, customer acquisition cost vs. lifetime value, and contribution margin by campaign. These are the numbers that tell you whether your marketing is working — not your click-through rate." }] },
      { _type: 'block', style: 'h2', _key: 'faq0', children: [{ _type: 'span', _key: 's8', text: 'Frequently Asked Questions' }] },
      { _type: 'block', style: 'h3', _key: 'faq1', children: [{ _type: 'span', _key: 's9', text: 'What is the difference between performance marketing and brand marketing?' }] },
      { _type: 'block', style: 'normal', _key: 'faq1a', children: [{ _type: 'span', _key: 's10', text: "Performance marketing is directly tied to measurable actions — a sale, a sign-up, a qualified lead. Brand marketing builds awareness and equity over time, with less direct measurement. The best strategies combine both, with each informing the other." }] },
      { _type: 'block', style: 'h3', _key: 'faq2', children: [{ _type: 'span', _key: 's11', text: 'Which platforms work best for performance marketing?' }] },
      { _type: 'block', style: 'normal', _key: 'faq2a', children: [{ _type: 'span', _key: 's12', text: "It depends on your audience and offer. Google Search captures demand. Meta creates it. LinkedIn works for B2B. The platform is secondary to having clean tracking, strong creative, and an offer that converts. Start with one platform and build from there." }] },
      { _type: 'block', style: 'h3', _key: 'faq3', children: [{ _type: 'span', _key: 's13', text: 'How much budget do I need to start?' }] },
      { _type: 'block', style: 'normal', _key: 'faq3a', children: [{ _type: 'span', _key: 's14', text: "There's no universal minimum, but we recommend enough budget to get statistically significant data within 30 days. For most B2C campaigns, that's ₹50,000–₹1,50,000/month. For B2B with longer cycles, budget requirements scale with lead cost and volume targets." }] },
    ],
  },
  {
    _id: 'dummy-4',
    title: 'Building Websites That Work as Infrastructure, Not Just Deliverables',
    slug: { current: 'dummy-websites-as-infrastructure' },
    heroImageUrl: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=1920&q=90&auto=format&fit=crop',
    excerpt: 'The shift from treating websites as one-time projects to building scalable digital platforms that evolve with your business.',
    publishedAt: '2024-12-20',
    categories: [{ _id: 'cat-web', title: 'Web & Platforms' }],
    author: { name: 'Digitally Next' },
    body: [
      { _type: 'block', style: 'normal', _key: 'b1', children: [{ _type: 'span', _key: 's1', text: "A website is not a deliverable. It is not a project with a start date and a launch day. It is infrastructure — and like all infrastructure, its value compounds when it is maintained, evolved, and integrated with the systems around it." }] },
      { _type: 'block', style: 'h2', _key: 'b2', children: [{ _type: 'span', _key: 's2', text: 'The Problem with the Project Mindset' }] },
      { _type: 'block', style: 'normal', _key: 'b3', children: [{ _type: 'span', _key: 's3', text: "When brands treat their website as a project, they invest heavily at launch and then let it stagnate. Speed degrades. Content goes stale. Conversion paths no longer match how the audience behaves. The website becomes a liability rather than an asset." }] },
      { _type: 'block', style: 'h2', _key: 'b4', children: [{ _type: 'span', _key: 's4', text: 'What Infrastructure Thinking Looks Like' }] },
      { _type: 'block', style: 'normal', _key: 'b5', children: [{ _type: 'span', _key: 's5', text: "Infrastructure thinking means your website is integrated with your CRM, analytics stack, and marketing automation from day one. Performance is monitored continuously. The team responsible for your website thinks about the next six months — not closing out a project ticket." }] },
      { _type: 'block', style: 'h2', _key: 'b6', children: [{ _type: 'span', _key: 's6', text: 'Platforms We Build On' }] },
      { _type: 'block', style: 'normal', _key: 'b7', children: [{ _type: 'span', _key: 's7', text: "We build on Next.js, WordPress, and Shopify depending on the business model. Each platform is chosen based on the scale requirements, content velocity, and integration needs — not developer preference." }] },
      { _type: 'block', style: 'h2', _key: 'faq0', children: [{ _type: 'span', _key: 's8', text: 'Frequently Asked Questions' }] },
      { _type: 'block', style: 'h3', _key: 'faq1', children: [{ _type: 'span', _key: 's9', text: 'How often should a website be rebuilt?' }] },
      { _type: 'block', style: 'normal', _key: 'faq1a', children: [{ _type: 'span', _key: 's10', text: "If you're rebuilding your website every 2–3 years, you're thinking about it as a project. Infrastructure doesn't get rebuilt — it gets evolved. With the right architecture, a website should improve continuously without requiring full rebuilds." }] },
      { _type: 'block', style: 'h3', _key: 'faq2', children: [{ _type: 'span', _key: 's11', text: 'Which CMS is best for scalable websites?' }] },
      { _type: 'block', style: 'normal', _key: 'faq2a', children: [{ _type: 'span', _key: 's12', text: "For content-heavy brands, headless CMS options like Sanity or Contentful offer the best long-term scalability. For e-commerce, Shopify's ecosystem is hard to beat. For flexibility with lower technical overhead, well-configured WordPress remains competitive." }] },
      { _type: 'block', style: 'h3', _key: 'faq3', children: [{ _type: 'span', _key: 's13', text: 'How do you measure website ROI?' }] },
      { _type: 'block', style: 'normal', _key: 'faq3a', children: [{ _type: 'span', _key: 's14', text: "We track conversion rate by traffic source, revenue per session, cost per acquisition, and core web vitals. These metrics together paint a clear picture of whether your website is working as a business asset or just as a digital presence." }] },
    ],
  },
  {
    _id: 'dummy-5',
    title: 'AI Enablement for Mid-Market Brands: Where to Start',
    slug: { current: 'dummy-ai-enablement' },
    heroImageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1920&q=90&auto=format&fit=crop',
    excerpt: "Not every brand needs a full AI overhaul. Here's how to identify the highest-leverage entry points for AI adoption in 2025.",
    publishedAt: '2024-12-05',
    categories: [{ _id: 'cat-ai', title: 'AI & Technology' }],
    author: { name: 'Digitally Next' },
    body: [
      { _type: 'block', style: 'normal', _key: 'b1', children: [{ _type: 'span', _key: 's1', text: "AI adoption doesn't have to mean a full technology overhaul. For mid-market brands, the highest-leverage entry points are often the smallest: automating one reporting workflow, using AI to draft and test ad copy at scale, or deploying a model that predicts churn before it happens." }] },
      { _type: 'block', style: 'h2', _key: 'b2', children: [{ _type: 'span', _key: 's2', text: 'Start With the Friction, Not the Hype' }] },
      { _type: 'block', style: 'normal', _key: 'b3', children: [{ _type: 'span', _key: 's3', text: "The best AI implementations start with a simple question: where does your team spend the most time on tasks that don't require human judgment? That's your first AI use case. Not a chatbot. Not a generative content engine. A targeted, measurable efficiency gain." }] },
      { _type: 'block', style: 'h2', _key: 'b4', children: [{ _type: 'span', _key: 's4', text: 'Building Toward a Data-Driven Culture' }] },
      { _type: 'block', style: 'normal', _key: 'b5', children: [{ _type: 'span', _key: 's5', text: "AI only compounds when it has clean data to work with. Before investing in AI tooling, invest in your data architecture. A well-structured CRM, clean event tracking, and consistent naming conventions will unlock more value from any AI tool than the tool itself." }] },
      { _type: 'block', style: 'h2', _key: 'b6', children: [{ _type: 'span', _key: 's6', text: 'AI Use Cases That Actually Work' }] },
      { _type: 'block', style: 'normal', _key: 'b7', children: [{ _type: 'span', _key: 's7', text: "Proven high-ROI AI applications for mid-market brands include: automated ad copy testing, predictive lead scoring, churn prediction models, dynamic pricing for e-commerce, and AI-assisted content briefs for SEO. Start with one, measure it, then expand." }] },
      { _type: 'block', style: 'h2', _key: 'faq0', children: [{ _type: 'span', _key: 's8', text: 'Frequently Asked Questions' }] },
      { _type: 'block', style: 'h3', _key: 'faq1', children: [{ _type: 'span', _key: 's9', text: 'Do we need a data science team to use AI?' }] },
      { _type: 'block', style: 'normal', _key: 'faq1a', children: [{ _type: 'span', _key: 's10', text: "For most mid-market use cases, no. Modern AI tools are built for marketers, not data scientists. You need someone who understands your data and your business goals — not someone who can build models from scratch." }] },
      { _type: 'block', style: 'h3', _key: 'faq2', children: [{ _type: 'span', _key: 's11', text: 'What is the biggest mistake brands make with AI?' }] },
      { _type: 'block', style: 'normal', _key: 'faq2a', children: [{ _type: 'span', _key: 's12', text: "Implementing AI before their data is clean. AI amplifies whatever you feed it — if your data is messy, inconsistent, or siloed, AI will amplify those problems, not solve them. Fix the data foundation first." }] },
      { _type: 'block', style: 'h3', _key: 'faq3', children: [{ _type: 'span', _key: 's13', text: 'How do we measure the ROI of AI tools?' }] },
      { _type: 'block', style: 'normal', _key: 'faq3a', children: [{ _type: 'span', _key: 's14', text: "Measure time saved per week, cost per outcome before and after, and error rate reduction. For revenue-impacting AI (like lead scoring or dynamic pricing), track direct revenue attribution. Set a 90-day review window before drawing conclusions." }] },
    ],
  },
];

export const DUMMY_CATEGORIES = [
  { _id: 'cat-strategy', title: 'Strategy' },
  { _id: 'cat-thought', title: 'Thought Leadership' },
  { _id: 'cat-perf', title: 'Performance' },
  { _id: 'cat-web', title: 'Web & Platforms' },
  { _id: 'cat-ai', title: 'AI & Technology' },
];
